<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="202405-01">
    <title>Python, PyPy3: Multiple Vulnerabilities</title>
    <synopsis>Multiple vulberabilities have been discovered in Python and PyPy3, the worst of which can lead to privilege escalation.</synopsis>
    <product type="ebuild">pypy3,pypy3_10,pypy3_9,python</product>
    <announced>2024-05-04</announced>
    <revised count="1">2024-05-04</revised>
    <bug>884653</bug>
    <bug>897958</bug>
    <bug>908018</bug>
    <bug>912976</bug>
    <bug>919475</bug>
    <bug>927299</bug>
    <access>remote</access>
    <affected>
        <package name="dev-lang/python" auto="yes" arch="*">
            <unaffected range="ge" slot="3.12">3.12.1</unaffected>
            <unaffected range="ge" slot="3.11">3.11.8</unaffected>
            <unaffected range="ge" slot="3.10">3.10.14</unaffected>
            <unaffected range="ge" slot="3.9">3.9.19</unaffected>
            <unaffected range="ge" slot="3.8">3.8.19</unaffected>
            <vulnerable range="lt" slot="3.12">3.12.1</vulnerable>
            <vulnerable range="lt" slot="3.11">3.11.8</vulnerable>
            <vulnerable range="lt" slot="3.10">3.10.14</vulnerable>
            <vulnerable range="lt" slot="3.9">3.9.19</vulnerable>
            <vulnerable range="lt" slot="3.8">3.8.19</vulnerable>
        </package>
        <package name="dev-python/pypy3" auto="yes" arch="*">
            <unaffected range="ge">7.3.16</unaffected>
            <vulnerable range="lt">7.3.16</vulnerable>
        </package>
        <package name="dev-python/pypy3_10" auto="yes" arch="*">
            <unaffected range="ge">7.3.16</unaffected>
            <vulnerable range="lt">7.3.16</vulnerable>
        </package>
        <package name="dev-python/pypy3_9" auto="yes" arch="*">
            <unaffected range="ge">7.3.16</unaffected>
            <vulnerable range="lt">7.3.16</vulnerable>
        </package>
    </affected>
    <background>
        <p>Python is an interpreted, interactive, object-oriented, cross-platform programming language.</p>
    </background>
    <description>
        <p>Multiple vulnerabilities have been discovered in Python, PyPy3. Please review the CVE identifiers referenced below for details.</p>
    </description>
    <impact type="high">
        <p>Please review the referenced CVE identifiers for details.</p>
    </impact>
    <workaround>
        <p>There is no known workaround at this time.</p>
    </workaround>
    <resolution>
        <p>All Python, PyPy3 users should upgrade to the latest version:</p>
        
        <code>
          # emerge --sync
          # emerge --ask --oneshot --verbose ">=dev-lang/python-3.12.1:3.12"
          # emerge --ask --oneshot --verbose ">=dev-lang/python-3.11.9:3.11"
          # emerge --ask --oneshot --verbose ">=dev-lang/python-3.10.14:3.10"
          # emerge --ask --oneshot --verbose ">=dev-lang/python-3.9.19:3.9"
          # emerge --ask --oneshot --verbose ">=dev-lang/python-3.8.19:3.8"
          # emerge --ask --oneshot --verbose ">=dev-python/pypy3-7.3.16"
          # emerge --ask --oneshot --verbose ">=dev-python/pypy3_10-7.3.16"
          # emerge --ask --oneshot --verbose ">=dev-python/pypy3_9-7.3.16"
        </code>
    </resolution>
    <references>
        <uri link="https://nvd.nist.gov/vuln/detail/CVE-2023-6507">CVE-2023-6507</uri>
        <uri link="https://nvd.nist.gov/vuln/detail/CVE-2023-6597">CVE-2023-6597</uri>
        <uri link="https://nvd.nist.gov/vuln/detail/CVE-2023-24329">CVE-2023-24329</uri>
        <uri link="https://nvd.nist.gov/vuln/detail/CVE-2023-40217">CVE-2023-40217</uri>
        <uri link="https://nvd.nist.gov/vuln/detail/CVE-2023-41105">CVE-2023-41105</uri>
        <uri link="https://nvd.nist.gov/vuln/detail/CVE-2024-0450">CVE-2024-0450</uri>
    </references>
    <metadata tag="requester" timestamp="2024-05-04T05:59:08.361678Z">graaff</metadata>
    <metadata tag="submitter" timestamp="2024-05-04T05:59:08.364851Z">graaff</metadata>
</glsa>